Translated environment.md into Japanese
konabuta/azureml-cheatsheets pull request #10
Opened 2021-07-11 15:51 UTC by k14i

# PR into Azure/azureml-cheatsheets

## Checklist

I have:

- [x] read and followed the [contributing guidelines](https://azure.github.io/azureml-cheatsheets/docs/misc/contributing)

## Changes

-

fixes #

2021-07-20 01:35 UTC, konabuta requested changes
大規模な翻訳作業ありがとうございます。リンク先の日本語への変更のみご対応お願い致します。

2021-07-20 01:35 UTC, konabuta commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/environment.md
> +`ScriptRunConfig` についてより詳しく知りたい場合は、[Running Code in the Cloud](script-run-config) をご覧ください。
リンク先も日本語に変更願います。

Running Code in the Cloud --> クラウド上でコードを実行する

2021-07-28 13:29 UTC, konabuta commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/environment.md
> +`ScriptRunConfig` についてより詳しく知りたい場合は、[Running Code in the Cloud](script-run-config) をご覧ください。
@k14i  こちらどうでしょうか？

2021-09-01 04:23 UTC, konabuta commented
@k14i  お時間ある時にレビューコメントをご確認ください！

2021-09-30 08:07 UTC, k14i commented
@konabuta mention に気づけていなくて大変失礼いたしました。（あとで通知の設定を見直しておきます。）
変更を push しましたので、ご確認願います。

2021-09-30 14:12 UTC, merged

2021-09-30 14:13 UTC, konabuta commented
ありがとうございました！