Translated run-history.md into Japanese
konabuta/azureml-cheatsheets pull request #11
Opened 2021-07-12 01:51 UTC by k14i

# PR into Azure/azureml-cheatsheets

## Checklist

I have:

- [x] read and followed the [contributing guidelines](https://azure.github.io/azureml-cheatsheets/docs/misc/contributing)

## Changes

-

fixes #

2021-07-20 01:55 UTC, konabuta requested changes
`微調整`の日本語の修正のみお願いします。

※ このページがサイドメニューに無かったので Issue でどこに配置すべきか聞いています。時間がかかりそうなので、この返答を待たずに進めたいと思います。
https://github.com/Azure/azureml-cheatsheets/issues/77

2021-07-20 01:55 UTC, konabuta commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/run-history.md
> +Experiment とは Run の集合体です。すべての Run は1つの Experiment に属します。通常、 Experiment は例えば「Bert-Large の微調整」といった特定の作業項目に関連付けられており、この目標に向かって反復することで、多数の Run を保有することになります。
微調整よりもカタカナでファインチューニングの方が自然だと思います。

2021-07-20 06:48 UTC, k14i commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/run-history.md
> +Experiment とは Run の集合体です。すべての Run は1つの Experiment に属します。通常、 Experiment は例えば「Bert-Large の微調整」といった特定の作業項目に関連付けられており、この目標に向かって反復することで、多数の Run を保有することになります。
修正してpushしました!

2021-07-26 00:46 UTC, konabuta commented
@k14i どうやらこのページは削除予定のようです...

2021-09-01 04:23 UTC, konabuta commented
本家の方で削除予定だとのことなので、申し訳ないですが、こちらクローズしちゃいます...

2021-09-01 04:23 UTC, closed without merging