Japanese contrib markdown cidev
konabuta/azureml-cheatsheets pull request #12
Opened 2021-08-03 00:51 UTC by konabuta

# PR into Azure/azureml-cheatsheets

## Checklist

I have:

- [ x] read and followed the [contributing guidelines](https://azure.github.io/azureml-cheatsheets/docs/misc/contributing)

## Changes

- Azure ML 上での開発に関する翻訳

fixes #

2021-09-01 04:22 UTC, konabuta commented
@k14i  @rsk800 どなたかレビューお願い致します！

2021-09-01 08:20 UTC, rsk800 requested changes
気になったのは細かい表記1点のみです。

2021-09-01 08:20 UTC, rsk800 commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/ci-dev.md
> +下記にてこれらの問題に対応するためのいくつかのテクニックと、Azure ML Compute を直接利用するメリットを紹介します。またこれらのテクニックを利用したい [例](#例) もいくつか提供します。
利用したい[例](#例)
↓
応用した[例](#例)？

2021-09-01 08:20 UTC, rsk800 commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/ci-dev.md
> +2. **"スケールダウンする前のアイドル時間 (秒)" の増加**
意味的にはスケールインなんですけど、原文そのままでもよいですかね。

2021-09-07 01:25 UTC, konabuta reviewed
利用したい -> 応用した
に修正しました。

2021-09-07 01:25 UTC, konabuta commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/ci-dev.md
> +2. **"スケールダウンする前のアイドル時間 (秒)" の増加**
そうですね...原文に忠実になりましょう...

2021-09-07 10:50 UTC, rsk800 approved these changes
lgtm

2021-09-14 02:45 UTC, merged