Translated into Japanese
konabuta/azureml-cheatsheets pull request #13
Opened 2021-08-22 14:12 UTC by rsk800

# PR into Azure/azureml-cheatsheets

## Checklist

I have:

- [ ] read and followed the [contributing guidelines](https://azure.github.io/azureml-cheatsheets/docs/misc/contributing)

## Changes

-

fixes #

2021-09-01 04:24 UTC, konabuta commented
ちょっと時間ください。解読頑張ります。。。

2021-09-14 02:33 UTC, konabuta commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/distributed-training.md
>  :::tip torch.nn.parallel.DistributedDataParallel vs torch.nn.DataParallel and torch.multiprocessing
and --> と

2021-09-14 02:44 UTC, konabuta requested changes
細かい点ですが、ご確認ください！

2021-09-14 02:44 UTC, konabuta commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/distributed-training.md
> +- PyTorch ジョブのために、Azure ML は Lightning が必要とする MASTER_ADDR、MASTER_PORT、and NODE_RANK 環境変数の制御を行います。
and --> と

2021-09-14 02:44 UTC, konabuta commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/distributed-training.md
> +### Hugging Face トランスフォーマー
HuggingFace 社が日本語訳を出していないので、正確なものは分からないですが、英語のまま使われることが多そうです。変更ご検討ください。

- Hugging Face トランスフォーマー  --> Hugging Face Transformers

2021-09-14 02:44 UTC, konabuta commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/distributed-training.md
> +Hugging Face は、`torch.distributed.launch`を使って分散トレーニングを実行するトランスフォーマーを使う際の多くの [サンプル](https://github.com/huggingface/transformers/tree/master/examples) を提供しています。Hugging Face トランスフォーマートレーナーAPIを使ってこれらのサンプ
HuggingFace 社が日本語訳を出していないので、正確なものは分からないですが、英語のまま使われることが多そうです。変更ご検討ください。

- トランスフォーマー  --> Transformers
- トランスフォーマートレーナーAPI --> Transformers Trainer API

2021-09-14 02:44 UTC, konabuta commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/distributed-training.md
> +`torch.distributed.launch`を使わずに、[per-process-launch](#distributeddataparallel-per-process-launch) オプションを使用して分散トレーニングを実行することもできます。このメソッドを使う際に気をつけることは、トランスフォーマー [TrainingArguments](https://huggingface.
HuggingFace 社が日本語訳を出していないので、正確なものは分からないですが、英語のまま使われることが多そうです。変更ご検討ください。

- トランスフォーマー  --> Transformers

2021-09-14 03:06 UTC, rsk800 commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/distributed-training.md
> +### Hugging Face トランスフォーマー
これは訳していて悩みました。ご指摘いただいた形が見た目的にきれいな気がするので統一しておきます。

2021-09-14 03:06 UTC, rsk800 commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/distributed-training.md
> +Hugging Face は、`torch.distributed.launch`を使って分散トレーニングを実行するトランスフォーマーを使う際の多くの [サンプル](https://github.com/huggingface/transformers/tree/master/examples) を提供しています。Hugging Face トランスフォーマートレーナーAPIを使ってこれらのサンプ
同上

2021-09-14 03:06 UTC, rsk800 commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/distributed-training.md
> +`torch.distributed.launch`を使わずに、[per-process-launch](#distributeddataparallel-per-process-launch) オプションを使用して分散トレーニングを実行することもできます。このメソッドを使う際に気をつけることは、トランスフォーマー [TrainingArguments](https://huggingface.
同上

2021-09-14 03:07 UTC, rsk800 commented
長文レビューしていただきありがとうございました。。
コメント頂いた点を直しました。

2021-09-21 13:39 UTC, merged

2021-09-21 13:39 UTC, konabuta commented
Merge 完了です！長文翻訳お疲れ様でした。