Translated data.md into Japanese
konabuta/azureml-cheatsheets pull request #16
Opened 2021-08-23 03:36 UTC by rsk800

# PR into Azure/azureml-cheatsheets

## Checklist

I have:

- [ ] read and followed the [contributing guidelines](https://azure.github.io/azureml-cheatsheets/docs/misc/contributing)

## Changes

-

fixes #

2021-09-01 04:21 UTC, konabuta requested changes
コメントしました。翻訳の変更、ご検討ください！

2021-09-01 04:21 UTC, konabuta commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/data.md
> +コードの中から`Datastore`のデータを参照します。例えば remote setting を使用する場合です。
remote setting の翻訳ですが、`リモート設定` の方が自然だと思いました。

2021-09-01 04:21 UTC, konabuta commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/data.md
> +- `dataset.as_mount(path_on_compute)` : remote run にデータセットをマウントする
`remote run` の翻訳ですが、`リモート実行時` の方が自然だと思いました。

2021-09-01 04:21 UTC, konabuta commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/data.md
> +- `dataset.as_download(path_on_compute)` : remote run にデータセットをダウンロードする
`remote run` の翻訳ですが、`リモート実行時` の方が自然だと思いました。

2021-09-01 04:21 UTC, konabuta commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/data.md
> +マウントモードで remote run からデータを参照する例:
`リモート実行時にデータを参照..` の方が自然だと思いました。

2021-09-14 03:20 UTC, rsk800 commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/data.md
> +コードの中から`Datastore`のデータを参照します。例えば remote setting を使用する場合です。
done

2021-09-14 03:22 UTC, rsk800 commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/data.md
> +- `dataset.as_mount(path_on_compute)` : remote run にデータセットをマウントする
そちらの方が自然だと思うので統一します。

2021-09-14 03:22 UTC, rsk800 commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/data.md
> +- `dataset.as_download(path_on_compute)` : remote run にデータセットをダウンロードする
同上

2021-09-14 03:22 UTC, rsk800 commented on website/i18n/ja/docusaurus-plugin-content-docs/current/cheatsheets/python/v1/data.md
> +マウントモードで remote run からデータを参照する例:
同上

2021-09-14 03:23 UTC, rsk800 commented
遅くなりましたが再度確認よろしくおねがいします

2021-09-21 13:38 UTC, merged

2021-09-21 13:38 UTC, konabuta commented
Merge 完了です！